apiVersion: apps/v1
kind: Deployment
metadata:
  name: storevault-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storevault-app
  template:
    metadata:
      labels:
        app: storevault-app
    spec:
      containers:
      - name: storevault-container
        image: your-docker-image-url:latest
        ports:
        - containerPort: 5000