apiVersion: apps/v1
kind: Deployment
metadata:
  name: storevault-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storevault-app
  template:
    metadata:
      labels:
        app: storevault-app
    spec:
      containers:
      - name: storevault-container
        image: 435240837203.dkr.ecr.ap-south-1.amazonaws.com/storevault:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: endpoint