apiVersion: apps/v1
kind: Deployment
metadata:
  name: storevault-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storevault-web
  template:
    metadata:
      labels:
        app: storevault-web
    spec:
      serviceAccountName: storevault-execution-sa
      containers:
      - name: application-container
        image: AWS_ACCOUNT_ID_PLACEHOLDER.dkr.ecr.AWS_REGION_PLACEHOLDER.amazonaws.com/storevault:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_HOST
          value: "DATABASE_HOST_PLACEHOLDER"
        - name: DATABASE_NAME
          value: "storevault"
        - name: DATABASE_USER
          value: "storevault_admin"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: storevault-database-credentials
              key: password