name: StoreVault Production Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPO_NAME }}
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{ vars.EKS_CLUSTER_NAME }}

      - name: Dynamic Token Replacement
        run: |
          RDS_ENDPOINT=$(aws rds describe-db-instances --db-instance-identifier storevault-production-db --region ${{ vars.AWS_REGION }} --query 'DBInstances[0].Endpoint.Address' --output text)
          AWS_ACCOUNT_ID="435240837203"
          sed -i "s/AWS_ACCOUNT_ID_PLACEHOLDER/$AWS_ACCOUNT_ID/g" k8s/serviceaccount.yaml
          sed -i "s/AWS_ACCOUNT_ID_PLACEHOLDER/$AWS_ACCOUNT_ID/g" k8s/deployment.yaml
          sed -i "s/AWS_REGION_PLACEHOLDER/${{ vars.AWS_REGION }}/g" k8s/deployment.yaml
          sed -i "s|DATABASE_HOST_PLACEHOLDER|$RDS_ENDPOINT|g" k8s/deployment.yaml

      - name: Deploy to EKS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPO_NAME }}
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          # Remove the webhook configuration that is blocking your deployment
          kubectl delete validatingwebhookconfigurations aws-load-balancer-webhook --ignore-not-found=true
          kubectl delete mutatingwebhookconfigurations aws-load-balancer-webhook --ignore-not-found=true
          
          # Apply your manifests
          kubectl apply -f k8s/
          
          # Update image
          kubectl set image deployment/storevault-deployment storevault-container=435240837203.dkr.ecr.ap-south-1.amazonaws.com/storevault:${{ github.run_number }}
          kubectl rollout status deployment/storevault-deployment