name: StoreVault Production Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPO_NAME }}
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{ vars.EKS_CLUSTER_NAME }}

      - name: Dynamic Token Replacement
        run: |
          RDS_ENDPOINT=$(aws rds describe-db-instances --db-instance-identifier storevault-production-db --region ${{ vars.AWS_REGION }} --query 'DBInstances[0].Endpoint.Address' --output text)
          
          # Create a temporary ConfigMap to hold the RDS endpoint
          # This is cleaner than sed-ing your deployment files
          kubectl create configmap db-config --from-literal=endpoint=$RDS_ENDPOINT -o yaml --dry-run=client | kubectl apply -f -

      - name: Deploy to EKS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPO_NAME }}
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          # 1. Apply manifests (ConfigMap, Service, etc)
          kubectl apply -f k8s/
          # 2. Update the image
          kubectl set image deployment/storevault-deployment storevault-container=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          # 3. Force restart to refresh variables
          kubectl rollout restart deployment/storevault-deployment
          # 4. Wait
          kubectl rollout status deployment/storevault-deployment --timeout=2m